swagger: "2.0"
info:
  version: "0.0.1"
  title: Chordial
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:

  /me:
    x-swagger-router-controller: users
    get:
      summary: user properties
      operationId: detailMe
      description: Sends user authentication token to spotify and gets user information
      parameters:
      - name: accessToken
        in: header
        required: false
        type: string
      responses:
        200:
          description: good authorization
          schema:
            $ref: '#/definitions/User'
        400:
          description: bad userID


  /me/friends:
    x-swagger-router-controller: users

    get:
      summary: list of friends
      operationId: detailFriends
      description: gets the list of friends and their Chordial information from database
      parameters:
      - name: accessToken
        in: header
        required: false
        type: string
      responses:
        200:
          description: user is logged in
          schema:
            type: array
            items:
              $ref: '#/definitions/User'

    post:
      summary: add friend
      operationId: addFriend
      description: get some friends
      parameters:
      - name: friendName
        in: body
        required: true
        schema:
          type: string
      - name: accessToken
        in: header
        required: false
        type: string
      responses:
        200:
          description: friend successfully added
          schema:
            type: string
        400:
          description: nobody likes you
          schema:
            type: string

  /me/music:
    x-swagger-router-controller: users

    get:
      summary: In-progress(lazy) placeholder for get tracks/playlists/etc.
      operationId: myMusic
      description: residentSleeper
      parameters:
      - name: accessToken
        in: header
        required: false
        type: string
      responses:
        200:
          description: I'm beyond sure this is ten times more work than actual coding
          schema:
            type: string

    delete:
      operationId: deleteMusic
      description: clears a user's list of top tracks
      parameters:
      - name: accessToken
        in: header
        required: false
        type: string
      responses:
        200:
          description: successfully deleted tracks
          schema:
            type: string

  /me/share/{idC}:
    x-swagger-router-controller: users

    get:
      summary: gets common songs between current user and other user
      operationId: shareCommon
      description: compares track arrays of each user and uses matching ids to return all common tracks
      parameters:
      - name: idC
        in: path
        required: true
        type: string
      - name: accessToken
        in: header
        required: false
        type: string
      responses:
        200:
          description: MANY A TRACK
          schema:
            type: array
            items:
              type: string

  /me/recommend:
    x-swagger-router-controller: users

    get:
      summary: gets song recommendations for user
      operationId: recommend
      description: sends user top tracks as seeds for spotify api recommendations
      parameters:
      - name: accessToken
        in: header
        required: false
        type: string
      responses:
        200:
          description: MANY A TRACK
          schema:
            type: array
            items:
              type: string

  /user:
    x-swagger-router-controller: users

    get:
      summary: gets all users
      operationId: getAll
      responses:
        200:
          description: returns users.find everything
          schema:
            type: array
            items:
              $ref: '#/definitions/User'

  /user/{userName}:
    x-swagger-router-controller: users

    get:
      operationId: getUser
      description: find user with given username
      parameters:
      - name: userName
        in: path
        type: string
        required: true
      responses:
        200:
          description: user found or not
          schema:
            type: string

  /user/authorizeTesting/{code}:
    x-swagger-router-controller: users

    get:
      summary: woo
      operationId: authorizeTesting
      description: akldjfkwe
      parameters:
      - name: code
        in: path
        type: string
        required: true
      responses:
        200:
          description: something works
          schema:
            type: string

  /user/tracks/{trackName}:
    x-swagger-router-controller: users

    post:
      summary: adds a track to user tracks
      operationId: addTrack
      description: adds a track
      parameters:
      - name: trackName
        in: path
        type: string
        required: true
      - name: userName
        in: body
        schema:
          type: string
      responses:
        200:
          description: track successfully added
          schema:
            type: string


  /user/callback:
    x-swagger-router-controller: users
    get:
      summary: authorizes user
      operationId: authorizeUser
      description: Gets authorization token from Spotify and sends it to the backend
      parameters:
      - name: code
        in: query
        required: true
        type: string
      responses:
        200:
          description: authentication successful, send user id to frontend
          schema:
            type: string
        400:
          description: the user failed to be authenticated


  /watchoutDELETEALL:
    x-swagger-router-controller: users
    delete:
      summary: RIP your database
      operationId: deleteThemAll
      description: R I P
      responses:
        200:
          description: deletion done
          schema:
            type: string

  /session:
    x-swagger-router-controller: songQueue
    get:
      operationId: isSession
      description: returns boolean true if session with given id exists, false if not
      parameters:
      - name: sessionID
        in: header
        required: true
        type: string
      responses:
        200:
          description: response sent
          schema:
            type: string

  /{sessionId}:
    x-swagger-router-controller: songQueue
    get:
      operationId: findSession
      description: Returns a session if it exists and error if not
      parameters:
      - name: sessionId
        in: path
        required: true
        type: string
      responses:
        200:
          description: sucessful response
          schema:
            type: string
    post:
      operationId: joinSession
      description: send user information to enter a chordial session
      parameters:
      - name: userName
        in: header
        type: string
        required: true
      - name: sessionId
        in: path
        required: true
        type: string
      responses:
        200:
          description: sucessfully joined sesssion
          schema:
            type: string
    delete:
      operationId: deleteSession
      description: removes a session from chordial memory
      parameters:
      - name: authorizationid
        in: header
        required: false
        type: string
      - name: sessionId
        in: path
        required: true
        type: string
      responses:
        200:
          description: sucessfully deleted
          schema:
            type: string

  /{sessionId}/start:
    x-swagger-router-controller: songQueue
    get:
      operationId: startSession
      description: initiallizes session queue with current users songs
      parameters:
      - name: sessionId
        in: path
        required: true
        type: string
      responses:
        200:
          description: send back populated queue
          schema:
            $ref: '#/definitions/Tracks'

  /{sessionId}/queueAction:
    x-swagger-router-controller: songQueue
    get:
      operationId: queueGetData
      description: stores data from frontend queue current state
      parameters:
      - name: getActionId
        in: header
        required: true
        type: string
      - name: actionData
        in: body
        required: false
        schema:
          type: string
      - name: sessionId
        in: path
        required: true
        type: string
      responses:
        200:
          description: server received information
          schema:
            type: string
    post:
      operationId: queueStoreData
      description: stores data from frontend queue current state
      parameters:
      - name: storeActionId
        in: header
        required: true
        type: string
      - name: sessionId
        in: path
        required: true
        type: string
      responses:
        201:
          description: server received information
          schema:
            type: string

  /{sessionId}/queue:
    x-swagger-router-controller: songQueue
    post:
      operationId: addToQueue
      description: adds track to position in queue
      parameters:
      - name: trackId
        in: header
        required: true
        type: string
      - name: sessionId
        in: path
        required: true
        type: string
      responses:
        201:
          description: track added to queue success
          schema:
            type: string
    delete:
      operationId: deleteFromQueue
      description: deletes a track from the session queue
      parameters:
      - name: trackId
        in: header
        required: true
        type: string
      - name: sessionId
        in: path
        required: true
        type: string
      responses:
        200:
          description: track deleted from queue
          schema:
            type: string


  /createSession:
    x-swagger-router-controller: songQueue
    get:
      operationId: createSession
      description: creates new session
      responses:
        200:
          description: new session created, returns Id of session
          schema:
            type: string


  /swagger:
    x-swagger-pipe: swagger_raw





# complex objects have schema definitions

definitions:
  Users:
    type: object
    required:
      - chordIDs
    properties:
      chordIDs:
        type: array
        items:
          type: string
          description: List of Chordial User's IDs
  User:
    type: object
    required:
      - spotifyID
      - chordialID
    properties:
      spotifyID:
        type: string
      chordialID:
        type: string
      friends:
        type: array
        items:
          type: string
          description: List of Chordial User's IDs
      tracks:
        type: array
        items:
          $ref: '#/definitions/Track'


  Tracks:
    type: object
    properties:
      urls:
        type: array
        items:
          type: string
          description: I don't know how tracks actually work

  Track:
    type: object
    properties:
      trackName:
        type: string
      trackID:
        type: string
